name: Build & publish Docker image to GHCR

on:
  push:
    branches: [ main ]        # não mude se você usa main

permissions:
  contents: read
  packages: write             # permite publicar no ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest    # runner gratuito (7 GB RAM)

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/transcriptseeker:latest
